- hosts: all
  gather_facts: yes
  vars_files:
    - cnc_values.yaml
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  tasks:
    - set_fact: 
        cnc_docker: "{{ cnc_docker }}"
        cnc_dgx: "{{ cnc_dgx }}"
        cnc_nvidia_driver: "{{ cnc_nvidia_driver }}"
        cnc_nvidia_vgpu: "{{ cnc_nvidia_vgpu }}"
        cnc_version: "{{ cnc_version }}"

    - name: Checking Nouveau is disabled
      become: true
      command: lsmod | grep nouveau
      register: nouveau_result
      failed_when: false

    - name: unload nouveau
      when: nouveau_result.rc != 0
      become: true
      modprobe:
        name: nouveau
        state: absent
      ignore_errors: true

    - name: blacklist nouveau
      when: nouveau_result.rc != 0
      become: true
      copy:
        dest: "/etc/modprobe.d/blacklist-nouveau.conf"
        owner: "root"
        group: "root"
        mode: "0644"
        content: |
          blacklist nouveau
          options nouveau modeset=0
      notify:
      - update-initramfs

  handlers:
    - name: update-initramfs
      become: true
      command: update-initramfs -u
      when: ansible_os_family == "Debian" and nouveau_result.rc != 0

- when: ansible_architecture == "aarch64"
  import_playbook: cnc-jetson.yaml
  name: Install Cloud Native Core on Jetson
  
- import_playbook: nvidia-driver.yaml
  when: "cnc_docker == true and cnc_nvidia_driver == true and ansible_architecture == 'x86_64'"

- when: "cnc_docker == true and ansible_architecture == 'x86_64'" 
  import_playbook: cnc-docker.yaml

- when: "cnc_version <= 4.1 and cnc_docker != true and ansible_architecture == 'x86_64'"
  import_playbook: older_versions/prerequisites.yaml

- when: "cnc_version <= 4.1 and cnc_docker != true and ansible_architecture == 'x86_64'"
  import_playbook: older_versions/cnc-installation.yaml

- when: "cnc_version > 4.1 and cnc_docker != true and ansible_architecture == 'x86_64'"
  import_playbook: prerequisites.yaml

- when: "cnc_version > 4.1 and cnc_docker != true and ansible_architecture == 'x86_64'"
  import_playbook: cnc-x86-install.yaml
