- hosts: master
  vars_files:
    - egx_values.yaml
  tasks:
   - name: Validate whether Kubernetes cluster installed
     shell: kubectl cluster-info
     register: k8sup
     no_log: True
     failed_when: false

   - name: Reset Kubernetes component
     become: true
     when: "'running' not in k8sup.stdout"
     shell: "kubeadm reset --force"
     register: reset_cluster
     no_log: True
     failed_when: false

   - name: remove etcd directory
     become: true
     when: "'running' not in k8sup.stdout"
     file:
       path: "/var/lib/etcd"
       state: absent

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd
     when: "egx_version == 4.0 or egx_version == 4.1 and 'running' not in k8sup.stdout"
     command: kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket=/run/containerd/containerd.sock
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm
     when: "egx_version == 1.3 or egx_version == 3.0 or egx_version == 3.1 and 'running' not in k8sup.stdout"
     command: kubeadm init --pod-network-cidr=192.168.0.0/16
     become: true
     register: kubeadm

   - name: Create kube directory
     when: "'running' not in k8sup.stdout"
     file:
      path: $HOME/.kube
      state: directory

   - name: admin permissions
     become: true
     file:
       path: /etc/kubernetes/admin.conf
       mode: '0644'

   - name: Copy kubeconfig to home
     when: "'running' not in k8sup.stdout"
     copy:
       remote_src: yes
       src:  /etc/kubernetes/admin.conf
       dest:  $HOME/.kube/config
       mode: '0600'

   - name: Install networking plugin to kubernetes cluster on EGX DIY Stack 3.1 or 4.0 or 4.1
     when: "egx_version == 3.1 or egx_version == 4.0  or egx_version == 4.1 and 'running' not in k8sup.stdout"
     command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

   - name: Install networking plugin to kubernetes cluster on EGX DIY Stack 2.0
     when: "'running' not in k8sup.stdout and egx_version == 2.0"
     command: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml

   - name: Install networking plugin to kubernetes cluster on EGX DIY Stack 1.2 or 1.3
     when: "egx_version == 1.2 or egx_version == 1.3 and 'running' not in k8sup.stdout"
     command: kubectl apply -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml

   - name: Update Networking Plugin for  on EGX DIY Stack 1.2 or 1.3
     when: "egx_version == 1.2 or egx_version == 1.3 and 'running' not in k8sup.stdout"
     command: kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true

   - name: Taint the Kubernetes Control Plane node
     when: "'running' not in k8sup.stdout"
     command: kubectl taint nodes --all node-role.kubernetes.io/master-

   - name: Generate join token
     become: true
     when: "'running' not in k8sup.stdout"
     shell: kubeadm token create --print-join-command
     register: kubeadm_join_cmd

   - set_fact:
       kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"
     when: "'running' not in k8sup.stdout"

   - name: Store join command
     when: "'running' not in k8sup.stdout"
     become: true
     copy: 
       content: "{{ kubeadm_join }}" 
       dest: "/tmp/kubeadm-join.command"

- hosts: nodes
  vars_files:
    - egx_values.yaml
  tasks:
   - name: Reset Kubernetes component
     become: true
     shell: "kubeadm reset --force"
     register: reset_cluster
     no_log: True
     failed_when: false

   - name: Create kube directory
     become: true
     file:
       path: /etc/kubernetes
       state: directory

   - name: Copy kubeadm-join command to node
     become: true
     copy:
       src: "/tmp/kubeadm-join.command"
       dest: "/tmp/kubeadm-join.command"
       
   - name: Get the Active Mellanox NIC on nodes
     when: "enable_network_operator == true and egx_version == 4.1"
     become: true
     shell: "for device in `sudo lshw -class network -short | grep -i ConnectX | awk '{print $2}' | egrep -v 'Device|path' | sed '/^$/d'`;do echo -n $device; sudo ethtool $device | grep -i 'Link detected'; done | grep yes | awk '{print $1}' > /tmp/$(hostname)-nic"
     register: node_nic

   - name: Copy Mellanox NIC Active File to master
     when: "enable_network_operator == true and egx_version == 4.1"
     become: true
     fetch:
       src: "/tmp/{{ ansible_nodename }}-nic"
       dest: "/tmp/"
       flat: yes


- hosts: nodes
  vars:
     kubeadm_join: "{{ lookup('file', '/tmp/kubeadm-join.command') }}"
  tasks:

   - name: Run kubeadm join
     become: true
     shell: "{{ kubeadm_join }}"

- hosts: master
  vars_files:
    - egx_values.yaml
  tasks:
   - name: Validate whether Kubernetes cluster installed
     shell: kubectl cluster-info
     register: k8sup
     no_log: True
     failed_when: false

   - name: Get Node name
     shell: "kubectl get nodes  | grep -v master | awk '{print $1}' | grep -v NAME"
     register: node_name
     no_log: True
     failed_when: false
     when: "'running' in k8sup.stdout"

   - name: Lable the node
     shell: "kubectl label node {{ item }} node-role.kubernetes.io/node="
     with_items: "{{ node_name.stdout_lines }}"
     when: "'running' in k8sup.stdout"
     no_log: True
     failed_when: false

   - name: Check If Helm is Installed
     shell: command -v helm >/dev/null 2>&1
     register: helm_exists
     no_log: True
     failed_when: false

   - name: "Install Helm on EGX DIY 1.2 or 2.0"
     become: true
     command: "{{ item }}"
     args:
       warn: false
     with_items:
       - curl -O https://get.helm.sh/helm-v3.1.0-linux-amd64.tar.gz
       - tar -xvzf helm-v3.1.0-linux-amd64.tar.gz
       - cp linux-amd64/helm /usr/bin/
       - rm -rf helm-v3.1.0-linux-amd64.tar.gz linux-amd64
     when: "egx_version == 1.2 or egx_version == 2.0 and helm_exists.rc > 0"

   - name: Installing the GPU Operator on EGX DIY 1.2 or 2.0
     become: true
     when: "egx_version == 1.2 or egx_version == 2.0 and 'running' in k8sup.stdout"
     command: "{{ item }}"
     args:
       warn: false
     with_items:
        - helm repo add nvidia https://nvidia.github.io/gpu-operator 
        - helm repo update
        - helm install --version 1.1.7 --devel nvidia/gpu-operator --wait --generate-name

   - name: "Install Helm on EGX DIY Stack 3.1 or 1.3"
     become: true
     command: "{{ item }}"
     args:
       warn: false
     with_items:
       - curl -O https://get.helm.sh/helm-v3.3.3-linux-amd64.tar.gz
       - tar -xvzf helm-v3.3.3-linux-amd64.tar.gz
       - cp linux-amd64/helm /usr/local/bin/
       - rm -rf helm-v3.3.3-linux-amd64.tar.gz linux-amd64
     when: "egx_version == 1.3 or egx_version == 3.1 and helm_exists.rc > 0"

   - name: "Install Helm on EGX DIY Stack 4.0"
     become: true
     command: "{{ item }}"
     args:
       warn: false
     with_items:
       - curl -O https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz
       - tar -xvzf helm-v3.5.4-linux-amd64.tar.gz
       - cp linux-amd64/helm /usr/local/bin/
       - rm -rf helm-v3.5.4-linux-amd64.tar.gz linux-amd64
     when: "egx_version == 4.0 and helm_exists.rc > 0"

   - name: "Install Helm on EGX DIY Stack 4.1"
     become: true
     command: "{{ item }}"
     args:
       warn: false
     with_items:
       - curl -O https://get.helm.sh/helm-v3.6.2-linux-amd64.tar.gz
       - tar -xvzf helm-v3.6.2-linux-amd64.tar.gz
       - cp linux-amd64/helm /usr/local/bin/
       - rm -rf helm-v3.6.2-linux-amd64.tar.gz linux-amd64
     when: "egx_version == 4.1 and helm_exists.rc > 0"

   - name: Checking Nouveau is disabled
     become: true
     command: lsmod | grep nouveau
     register: nouveau_result
     failed_when: false

   - name: Alert
     when: nouveau_result.rc != 1
     failed_when: false
     debug:
       msg: "Please reboot the host and run the same command again"

   - name: Checking if Network Operator is installed
     shell: helm ls -A | grep network-operator
     register: network_operator
     failed_when: false
     no_log: True

   - name: Get the Active Mellanox NIC on master
     when: "enable_network_operator == true and egx_version == 4.1 and network_operator.rc == 1 and 'running' in k8sup.stdout"
     become: true
     failed_when: false
     shell: "for device in `sudo lshw -class network -short | grep -i ConnectX | awk '{print $2}' | egrep -v 'Device|path' | sed '/^$/d'`;do echo -n $device; sudo ethtool $device | grep -i 'Link detected'; done | grep yes | awk '{print $1}' > /tmp/$(hostname)-nic"

   - name: List Mellanox Active NICs
     when: "enable_network_operator == true and egx_version == 4.1 and network_operator.rc == 1 and 'running' in k8sup.stdout"
     failed_when: false
     shell: "for list in `ls -lrt /tmp/*nic | awk '{print $NF}'`; do cat $list | tr '\n' ','; done | sed 's/.$//'"
     register: active_nic

   - name: Update Active mellanox NIC in network-operator-values.yaml
     when: "enable_network_operator == true and egx_version == 4.1 and network_operator.rc == 1 and 'running' in k8sup.stdout"
     failed_when: false
     shell: 'sed -ie "s/devices: \[.*\]/devices: \\[ {{ active_nic.stdout }}\]/g" $PWD/egx-platform/playbooks/network-operator-values.yaml'
     args:
       warn: false

   - name: Installing the Network Operator on EGX DIY Stack 4.1
     when: "enable_network_operator == true and egx_version == 4.1 and network_operator.rc == 1 and 'running' in k8sup.stdout"
     shell: "{{ item }}"
     args:
       warn: false
     with_items:
        - helm repo add mellanox https://mellanox.github.io/network-operator --force-update
        - helm repo update
        - kubectl label nodes --all node-role.kubernetes.io/master- --overwrite
        - helm install -f $PWD/egx-platform/playbooks/network-operator-values.yaml -n network-operator --create-namespace --wait network-operator mellanox/network-operator

   - name: Checking if GPU Operator is installed
     shell: helm ls -A | grep gpu-operator
     register: gpu_operator
     failed_when: false
     no_log: True

   - name: Checking if Network Operator is installed
     shell: helm ls -A | grep network-operator
     register: network_operator_valid
     failed_when: false
     no_log: True

   - name: Installing the GPU Operator on EGX DIY Stack 3.1
     when: "egx_version == 1.3 or egx_version == 3.1 and gpu_operator.rc == 1 and 'running' in k8sup.stdout"
     command: "{{ item }}"
     args:
       warn: false
     with_items:
        - helm repo add nvidia https://helm.ngc.nvidia.com/nvidia --force-update
        - helm repo update
        - helm install --version 1.6.2 --devel nvidia/gpu-operator --wait --generate-name

   - name: Installing the GPU Operator on EGX DIY Stack 4.0
     when: "egx_version == 4.0 and gpu_operator.rc == 1 and 'running' in k8sup.stdout"
     command: "{{ item }}"
     args:
       warn: false
     with_items:
        - helm repo add nvidia https://helm.ngc.nvidia.com/nvidia --force-update
        - helm repo update
        - helm install --version 1.7.0 --devel nvidia/gpu-operator --set operator.defaultRuntime=containerd --wait --generate-name


   - name: Install GPU Operator with vGPU
     when: "enable_vgpu == true and egx_version == 4.1 and gpu_operator.rc == 1 and 'running' in k8sup.stdout"
     args:
       warn: false
     shell: "{{ item }}"
     with_items:
        - kubectl create namespace gpu-operator-resources
        - kubectl create configmap licensing-config -n gpu-operator-resources --from-file=gridd.conf
        - kubectl create secret docker-registry registry-secret --docker-server='{{ gpu_operator_driver_registry }}' --docker-username='{{ gpu_operator_registry_username }}' --docker-password={{ gpu_operator_registry_password }} --docker-email={{ gpu_operator_registry_email }} -n gpu-operator-resources
        - helm repo add nvidia https://helm.ngc.nvidia.com/nvidia --force-update
        - helm repo update
        - helm install --version 1.8.0 --devel nvidia/gpu-operator --set operator.defaultRuntime=containerd --set driver.repository='{{ gpu_operator_driver_registry }}' --set driver.version='{{ gpu_operator_driver_version }}' --set driver.imagePullSecrets[0]=registry-secret --set driver.licensingConfig.configMapName=licensing-config --wait --generate-name


   - name: Installing the GPU Operator on EGX DIY Stack 4.1
     when: "enable_vgpu == false and egx_version == 4.1 and gpu_operator.rc == 1 and network_operator_valid.rc == 1 and enable_mig == false and 'running' in k8sup.stdout"
     shell: "{{ item }}"
     args:
       warn: false
     with_items:
        - helm repo add nvidia https://helm.ngc.nvidia.com/nvidia --force-update
        - helm repo update
        - helm install --version 1.8.0 --devel nvidia/gpu-operator --set operator.defaultRuntime=containerd --wait --generate-name

   - name: Installing the GPU Operator with RDMA on EGX DIY Stack 4.1
     when: "enable_vgpu == false and egx_version == 4.1 and gpu_operator.rc == 1 and network_operator_valid.rc == 0 and enable_mig == false and 'running' in k8sup.stdout"
     shell: "{{ item }}"
     args:
       warn: false
     with_items:
        - helm repo add nvidia https://helm.ngc.nvidia.com/nvidia --force-update
        - helm repo update
        - helm install --version 1.8.0 --devel nvidia/gpu-operator --set operator.defaultRuntime=containerd --set driver.rdma.enabled=true --wait --generate-name 

   - name: Installing the GPU Operator with MIG on EGX DIY Stack 4.1
     when: "enable_vgpu == false and egx_version == 4.1 and gpu_operator.rc == 1 and network_operator_valid.rc == 1 and enable_mig == true and 'running' in k8sup.stdout"
     shell: "{{ item }}"
     args:
       warn: false
     with_items:
        - helm repo add nvidia https://helm.ngc.nvidia.com/nvidia --force-update
        - helm repo update
        - helm install --version 1.8.0 --devel nvidia/gpu-operator --set operator.defaultRuntime=containerd --wait --set mig.strategy=single --generate-name
        - kubectl label nodes --all nvidia.com/mig.config={{ mig_profile }} --overwrite

   - name: Installing the GPU Operator with MIG and RDMA on EGX DIY Stack 4.1
     when: "enable_vgpu == false and egx_version == 4.1 and gpu_operator.rc == 1 and network_operator_valid.rc == 0 and enable_mig == true and 'running' in k8sup.stdout"
     shell: "{{ item }}"
     args:
       warn: false
     with_items:
        - helm repo add nvidia https://helm.ngc.nvidia.com/nvidia --force-update
        - helm repo update
        - helm install --version 1.8.0 --devel nvidia/gpu-operator --set operator.defaultRuntime=containerd --set driver.rdma.enabled=true --set mig.strategy=single --wait --generate-name
        - kubectl label nodes --all nvidia.com/mig.config={{ mig_profile }} --overwrite

