- hosts: master
  vars_files:
    - cnc_values.yaml
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  tasks:
   - name: Validate whether Kubernetes cluster installed
     shell: kubectl cluster-info
     register: k8sup
     no_log: True
     failed_when: false

   - name: Reset Kubernetes component
     become: true
     shell: "kubeadm reset --force"
     no_log: True
     failed_when: false

   - name: remove etcd directory
     become: true
     when: "'running' not in k8sup.stdout"
     file:
       path: "/var/lib/etcd"
       state: absent

   - name: Check proxy conf exists
     when: proxy == true
     lineinfile:
       path: /etc/environment
       regexp: '^http_proxy=*'
       state: absent
     check_mode: yes
     changed_when: false
     register: proxyconf

   - name: Get Host IP
     shell: interface=$(ip a | grep 'state UP' |  egrep 'enp*|ens*|eno*|enc*|eth*|bond*|wlan*' | awk '{print $2}' | sed 's/://g'); for i in $interface; do ifconfig $i | grep -iw inet | awk '{print $2}'; done
     register: network

   - name: subnet information
     shell: "echo {{ network.stdout_lines[0] }} | cut -d. -f1-3"
     register: subnet

   - name: add proxy lines to environment
     when: proxy == true and not proxyconf.found
     become: true
     lineinfile:
       dest: /etc/environment
       insertafter: "PATH="
       line: "{{ item }}"
     loop:
       - http_proxy={{ http_proxy }}
       - HTTP_PROXY={{ http_proxy }}
       - https_proxy={{ https_proxy }}
       - HTTPS_PROXY={{ https_proxy }}
       - no_proxy={{ network.stdout_lines[0] }},localhost,127.0.0.0/8,10.96.0.1/24,10.244.0.0/16,192.168.32.0/22,{{ subnet.stdout }}.0/24
       - NO_PROXY={{ network.stdout_lines[0] }},localhost,127.0.0.0/8,10.96.0.1/24,10.244.0.0/16,192.168.32.0/22,{{ subnet.stdout }}.0/24

   - name: source the env
     when: proxy == true and not proxyconf.found
     shell: source /etc/environment
     args:
       executable: /bin/bash

   - name: check default gateway
     shell: ip r | grep default
     failed_when: false
     register: gateway
     when: proxy == true

   - name: add default gateway
     shell: route add -net 0.0.0.0/0 gw {{ network.stdout_lines[0] }}
     when: gateway.rc | default ('') == 1 and proxy == true

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 5.0
     when: "cnc_version == 5.2 or cnc_version == 5.1 or cnc_version == 5.0 and 'running' not in k8sup.stdout"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v1.22.5" --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 6.0
     when: "'running' not in k8sup.stdout and cnc_version == 6.0"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v1.23.2" --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 6.1
     when: "'running' not in k8sup.stdout and proxy == false and cnc_version == 6.1"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v1.23.5" --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 6.1
     when: "'running' not in k8sup.stdout and proxy == true and cnc_version == 6.1"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v1.23.5" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 6.2
     when: "'running' not in k8sup.stdout and proxy == false and cnc_version == 6.2"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v1.23.7" --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 6.3
     when: "'running' not in k8sup.stdout and proxy == false and cnc_version == 6.3"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v1.23.9" --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 7.0
     when: "'running' not in k8sup.stdout and  proxy == false and cnc_version == 7.0 and ansible_distribution_major_version == '22'"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:/run/containerd/containerd.sock --kubernetes-version="v1.24.2" --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 7.1
     when: "'running' not in k8sup.stdout and  proxy == false and cnc_version == 7.1 and ansible_distribution_major_version == '22'"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:/run/containerd/containerd.sock --kubernetes-version="v1.24.6" --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 8.0
     when: "'running' not in k8sup.stdout and  proxy == false and cnc_version == 8.0 and ansible_distribution_major_version == '22'"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:/run/containerd/containerd.sock --kubernetes-version="v1.25.2" --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 6.2
     when: "'running' not in k8sup.stdout and proxy == true and cnc_version == 6.2"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v1.23.7" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 6.3
     when: "'running' not in k8sup.stdout and proxy == true and cnc_version == 6.3"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v1.23.12" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 7.0
     when: "'running' not in k8sup.stdout and proxy == true and cnc_version == 7.0 and ansible_distribution_major_version == '22'"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:/run/containerd/containerd.sock --kubernetes-version="v1.24.2" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 7.1
     when: "'running' not in k8sup.stdout and proxy == true and cnc_version == 7.1 and ansible_distribution_major_version == '22'"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:/run/containerd/containerd.sock --kubernetes-version="v1.24.6" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Iniitialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Core 8.0
     when: "'running' not in k8sup.stdout and proxy == true and cnc_version == 8.0 and ansible_distribution_major_version == '22'"
     command: kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:/run/containerd/containerd.sock --kubernetes-version="v1.25.2" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}
     become: true
     register: kubeadm

   - name: Create kube directory
     when: "'running' not in k8sup.stdout"
     file:
      path: $HOME/.kube
      state: directory

   - name: admin permissions
     become: true
     file:
       path: /etc/kubernetes/admin.conf
       mode: '0644'

   - name: Copy kubeconfig to home
     when: "'running' not in k8sup.stdout"
     copy:
       remote_src: yes
       src:  /etc/kubernetes/admin.conf
       dest:  $HOME/.kube/config
       mode: '0600'

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Core 7.1 or 8.0
     when: "'running' not in k8sup.stdout and cnc_version >= 7.1 and ansible_distribution_major_version == '22'"
     command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Core 7.0
     when: "'running' not in k8sup.stdout and cnc_version == 7.0 and ansible_distribution_major_version == '22'"
     command: kubectl apply -f https://projectcalico.docs.tigera.io/archive/v3.23/manifests/calico.yaml

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Core > 6.3
     when: "'running' not in k8sup.stdout and cnc_version >= 6.3 and ansible_distribution_major_version == '20'"
     command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Core < 6.2
     when: "'running' not in k8sup.stdout and cnc_version <= 6.2 and ansible_distribution_major_version == '20'"
     command: kubectl apply -f https://projectcalico.docs.tigera.io/archive/v3.21/manifests/calico.yaml

   - name: Update Network plugin for Calico on NVIDIA Cloud Native Core > 3.1
     when: "'running' not in k8sup.stdout and cnc_version >= 3.1 "
     shell: "sleep 5; kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=interface=ens*,eth*,enc*,bond*,enp*,eno*"

   - name: Taint the Kubernetes Control Plane node
     when: "'running' not in k8sup.stdout and cnc_version < 7.0"
     command: kubectl taint nodes --all node-role.kubernetes.io/master-

   - name: Taint the Kubernetes Control Plane node
     when: "'running' not in k8sup.stdout and cnc_version == 7.0 or 'running' not in k8sup.stdout and cnc_version == 7.1"
     command: kubectl taint nodes --all node-role.kubernetes.io/master- node-role.kubernetes.io/control-plane-

   - name: Taint the Kubernetes Control Plane node
     when: "'running' not in k8sup.stdout and cnc_version == 8.0"
     command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

   - name: Generate join token
     become: true
     when: "'running' not in k8sup.stdout"
     shell: kubeadm token create --print-join-command
     register: kubeadm_join_cmd

   - set_fact:
       kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"
     when: "'running' not in k8sup.stdout"

   - name: Store join command
     when: "'running' not in k8sup.stdout"
     become: true
     copy:
       content: "{{ kubeadm_join }}"
       dest: "/tmp/kubeadm-join.command"

   - name: Store Kubernetes cluster status
     become: true
     copy:
       content: "{{ k8sup.stdout }}"
       dest: "/tmp/k8sup.status"

- hosts: nodes
  vars_files:
    - cnc_values.yaml
  tasks:
   - name: Copy kubernetes cluster status
     become: true
     copy:
       src: "/tmp/k8sup.status"
       dest: "/tmp/k8sup.status"

   - name: Search for Kubernetes status
     become: true
     register: k8sup
     shell: "cat /tmp/k8sup.status"

   - name: Reset Kubernetes component
     become: true
     shell: "kubeadm reset --force"
     register: reset_cluster
     failed_when: false
     when: "'running' not in k8sup.stdout"

   - name: Create kube directory
     become: true
     file:
       path: /etc/kubernetes
       state: directory

   - name: Copy kubeadm-join command to node
     become: true
     copy:
       src: "/tmp/kubeadm-join.command"
       dest: "/tmp/kubeadm-join.command"

   - name: Get the Active Mellanox NIC on nodes
     when: "enable_network_operator == true and cnc_version >= 4.1"
     become: true
     shell: "for device in `sudo lshw -class network -short | grep -i ConnectX | awk '{print $2}' | egrep -v 'Device|path' | sed '/^$/d'`;do echo -n $device; sudo ethtool $device | grep -i 'Link detected'; done | grep yes | awk '{print $1}' > /tmp/$(hostname)-nic"
     register: node_nic

   - name: Copy Mellanox NIC Active File to master
     when: "enable_network_operator == true and cnc_version >= 4.1"
     become: true
     fetch:
       src: "/tmp/{{ ansible_nodename }}-nic"
       dest: "/tmp/"
       flat: yes


- hosts: nodes
  vars:
     kubeadm_join: "{{ lookup('file', '/tmp/kubeadm-join.command') }}"
  tasks:

   - name: Search for Kubernetes status
     become: true
     register: k8sup
     shell: "cat /tmp/k8sup.status"

   - name: Run kubeadm join
     become: true
     shell: "{{ kubeadm_join }}"
     when: "'running' not in k8sup.stdout"