- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - cnc_values.yaml
  tasks:

    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
          - apt-utils
          - aptitude
          - unzip
          - pkg-config
          - build-essential
        state: latest
        update_cache: true

    - name: Check NVIDIA Driver Modules are loaded
      shell: "lsmod | grep -i nvidia"
      register: nvidia_mod
      no_log: True
      failed_when: false

    - name: Install NVIDIA vGPU Driver
      become: true
      when:  nvidia_mod.rc == 1
      block:

        - name: Download the NGC CLI
          get_url:
            url: https://ngc.nvidia.com/downloads/ngccli_linux.zip
            dest: /tmp/

        - name: Unzip the NGC CLI
          unarchive:
            src: /tmp/ngccli_linux.zip
            remote_src: true
            dest: /usr/local/bin/

        - name: Update the NGC CLI permissions
          file:
            path: /usr/local/bin/ngc
            mode: 0775

        - name: NGC Config Set
          shell: export NGC_CLI_API_KEY={{ ngc_api_key }} && ngc config set --format_type=ascii --org=nvaie --team=no-team

        - name: Download the NVIDIA vGPU Driver from NGC
          shell: export NGC_CLI_API_KEY={{ ngc_api_key }} && ngc registry resource download-version "nvaie/vgpu_guest_driver_2_0:510.47.03"

        - name: Update vGPU Driver Permissions
          file:
            path: ./vgpu_guest_driver_2_0_v510.47.03/NVIDIA-Linux-x86_64-510.47.03-grid.run
            mode: '0777'

        - name: Install the vGPU Driver
          shell: sh ./vgpu_guest_driver_2_0_v510.47.03/NVIDIA-Linux-x86_64-510.47.03-grid.run -s

        - name: Download the vGPU token
          shell: export NGC_CLI_API_KEY={{ ngc_api_key }} && ngc registry resource download-version "nvlp-aienterprise/licensetoken:1"

        - name: Clear NGC Config
          shell: ngc config clear

        - name: Clear vGPU files
          file:
            path: ./vgpu_guest_driver_2_0_v510.47.03/NVIDIA-Linux-x86_64-510.47.03-grid.run
            state: absent

        - name: Check NVIDIA Driver Modules are loaded
          ignore_errors: true
          copy:
            src: "{{ item }}"
            dest: /etc/nvidia/ClientConfigToken/
          with_fileglob: "{{lookup('pipe', 'pwd')}}/licensetoken_v1/client_configuration_token*.tok"

        - name: clear vGPU Token
          file:
            path: ./licensetoken_v1
            state: absent
            
        - name: create a gridd.conf for vGPU
          copy:
            dest: /etc/nvidia/gridd.conf
            content: |
              FeatureType=1

    - name: Reboot the system
      when:  nvidia_mod.rc == 1
      reboot:
        reboot_timeout: 900

    - name: Restart vGPU gridd service
      when:  nvidia_mod.rc == 1
      service:
        name: nvidia-gridd
        state: restarted
