- hosts: all
  become: true
  vars_files:
    - cnc_values.yaml
  become_method: sudo
  tasks:

    - name: Check NVIDIA Driver Modules are loaded
      shell: "lsmod | grep -i nvidia"
      register: nvidia_mod
      no_log: True
      failed_when: false

    - name: NVIDIA Driver Clean Up
      when:  cnc_version >= 6.1 and nvidia_mod.rc >= 1
      block:
        - name: Remove Ubuntu unattended upgrades to prevent apt lock
          ansible.builtin.apt:
            name: unattended-upgrades
            state: absent
            purge: yes
          register: apt_cleanup
          retries: 10
          until: apt_cleanup is success

        - name: Remove OLD Apt Repository
          apt_repository:
            repo: ppa:graphics-drivers/ppa
            state: absent
          register: ppa_clean
          retries: 10
          until: ppa_clean is success

        - name: Remove NVIDIA packages
          apt:
            name:
            - "*cuda*"
            - "*nvidia*"
            - "gdm*"
            - "xserver-xorg-core"
            autoremove: yes
            purge: yes
            state: absent
          register: nvidia_cleanup
          retries: 10
          until: nvidia_cleanup is success

        - name: Remove old keyring
          shell:
            cmd: "apt-key del 7fa2af80"

    - name: Install NVIDIA TRD Driver on NVIDIA Cloud Native Core 6.1
      become: true
      when:  nvidia_mod.rc >= 1 and cnc_version <= 6.1 and ansible_architecture == 'x86_64'
      block:
        - name: Get Apt Key
          get_url:
            url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
            dest: /tmp/3bf863cc.pub
            mode: 0664

        - name: Add NVIDIA Driver APT key
          shell: cat /tmp/3bf863cc.pub | apt-key add

        - name: Get OLD Apt Key
          get_url:
            url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
            dest: /tmp/7fa2af80.pub
            mode: 0664

        - name: Add OLD NVIDIA Driver APT key
          shell: cat /tmp/7fa2af80.pub | apt-key add

        - name: Install TRD Driver
          apt:
            deb: https://us.download.nvidia.com/tesla/510.47.03/nvidia-driver-local-repo-ubuntu2004-510.47.03_1.0-1_amd64.deb
            state: present
            update_cache: yes

        - name: Install NVIDIA CUDA Drivers
          ignore_errors: true
          apt:
            name: cuda-drivers
            update_cache: yes
            state: latest

    - name: Install NVIDIA TRD Driver
      become: true
      when:  cnc_version == 6.2 and nvidia_mod.rc >= 1 and ansible_architecture == 'x86_64' or cnc_version == 7.0 and nvidia_mod.rc >= 1 and ansible_architecture == 'x86_64'
      block:
        - name: Install NVIDIA TRD Drivers
          ignore_errors: true
          apt:
            name: ['nvidia-driver-515', 'nvidia-dkms-515']
            update_cache: yes
            state: latest

    - name: Install NVIDIA TRD Driver
      become: true
      when:  "cnc_version == 6.1 and nvidia_mod.rc >= 1 and ansible_architecture == 'aarch64' or cnc_version == 6.2 and nvidia_mod.rc >= 1 and ansible_architecture == 'aarch64'"
      block:
        - name: Get NVIDIA Driver Apt Key
          get_url:
            url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-ubuntu2004.pin
            dest: /etc/apt/preferences.d/cuda-repository-pin-600
            mode: 0664

        - name: Get NVIDIA Driver
          get_url:
            url: https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-ubuntu2004-11-7-local_11.7.0-515.43.04-1_arm64.deb
            dest: /tmp/cuda-repo-ubuntu2004-11-7-local_11.7.0-515.43.04-1_arm64.deb
            mode: 0664

        - name: Install NVIDIA Driver
          shell: "{{ item }}"
          with_items:
            - dpkg -i /tmp/cuda-repo-ubuntu2004-11-7-local_11.7.0-515.43.04-1_arm64.deb
            - cp /var/cuda-repo-ubuntu2004-11-7-local/cuda-*-keyring.gpg /usr/share/keyrings/

    - name: Install NVIDIA TRD Keys
      become: true
      when:  nvidia_mod.rc >= 1 and cnc_version == 7.0 and ansible_architecture == 'aarch64'
      block:
        - name: Get NVIDIA Driver Apt Key
          get_url:
            url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/sbsa/cuda-ubuntu2204.pin
            dest: /etc/apt/preferences.d/cuda-repository-pin-600
            mode: 0664

        - name: Get NVIDIA Driver
          get_url:
            url: https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-ubuntu2204-11-7-local_11.7.0-515.43.04-1_arm64.deb
            dest: /tmp/cuda-repo-ubuntu2204-11-7-local_11.7.0-515.43.04-1_arm64.deb
            mode: 0664

        - name: Install NVIDIA Driver
          shell: "{{ item }}"
          with_items:
            - dpkg -i /tmp/cuda-repo-ubuntu2204-11-7-local_11.7.0-515.43.04-1_arm64.deb
            - cp /var/cuda-repo-ubuntu2204-11-7-local/cuda-*-keyring.gpg /usr/share/keyrings/

    - name: Add CUDA APT Key
      become: true
      when:  "cnc_version == 6.3 and nvidia_mod.rc >= 1 and ansible_architecture == 'x86_64"
      apt:
        deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
        state: "present"
      register: cuda_ring
      retries: 10
      until: cuda_ring is success

    - name: Add CUDA APT Key
      become: true
      when:  "cnc_version == 7.1 and nvidia_mod.rc >= 1 and ansible_architecture == 'x86_64' or cnc_version == 8.0 and nvidia_mod.rc >= 1 and ansible_architecture == 'x86_64'"
      apt:
        deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
        state: "present"
      register: cuda_ring
      retries: 10
      until: cuda_ring is success

    - name: Add CUDA APT Key
      become: true
      when:  "cnc_version == 6.3 and nvidia_mod.rc >= 1 and ansible_architecture == 'aarch64'"
      apt:
        deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-keyring_1.0-1_all.deb
        state: "present"
      register: cuda_ring
      retries: 10
      until: cuda_ring is success

    - name: Install NVIDIA TRD Driver
      become: true
      when:  "cnc_version == 7.1 and nvidia_mod.rc >= 1 and ansible_architecture == 'aarch64' or cnc_version == 8.0 and nvidia_mod.rc >= 1 and ansible_architecture == 'aarch64'"
      apt:
        deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/sbsa/cuda-keyring_1.0-1_all.deb
        state: "present"
      register: cuda_ring
      retries: 10
      until: cuda_ring is success

    - name: Install NVIDIA TRD Driver
      become: true
      when:  "nvidia_mod.rc >= 1 and cnc_version == 6.3 or nvidia_mod.rc >= 1 and cnc_version == 7.1 or nvidia_mod.rc >= 1 and cnc_version == 8.0"
      ignore_errors: true
      block:
        - name: Force an apt update
          apt:
            update_cache: true
          changed_when: false
          register: update
          retries: 10
          until: update is success

        - name: Ensure kmod is installed
          apt:
            name: "kmod"
            state: "present"
          register: kmod_check
          retries: 10
          until: kmod_check is success

        - name: Temporarily adjust account password policy to allow for successful NVIDIA driver install
          shell: chage -d 1 root

        - name: Install driver packages
          apt:
            name: cuda
            state: present
          register: cuda_install
          retries: 10
          until: cuda_install is success

        - name: Setup root account password policy
          shell: chage -d 0 root

    - name: Reboot the system
      when:  nvidia_mod.rc >= 1
      reboot:
        reboot_timeout: 900